baseurl = "https://blog.8-p.info/en/"
languageCode = "en-us"
title = "Kazu's Log"
theme = "x17"
paginate = 3

canonifyURLs = true

[permalinks]
posts  = "/:year/:month/:day/:filename/"
pages  = "/:filename/"

[outputs]
home = ["html", "rss", "json"]

[params]
SourceRoot = "https://github.com/kzys/blog/tree/master/en"
