baseurl = "https://blog.8-p.info/en/"
languageCode = "en-us"
title = "Kazu's Log"
theme = "x17"

[permalinks]
post  = "/:year/:month/:day/:filename/"
page  = "/:filename/"

[outputs]
home = ["html", "rss", "json"]
