baseurl = "https://blog.8-p.info/en/"
languageCode = "en-us"
title = "blog.8-p.info"
theme = "x17"
paginate = 5

canonifyURLs = true

[markup.highlight]
style = "github"

[markup.goldmark.renderer]
unsafe = true

[permalinks]
posts  = "/:year/:month/:day/:filename/"
pages  = "/:filename/"

[outputs]
home = ["html", "rss", "json"]

[params]
SourceRoot = "https://github.com/kzys/blog/tree/master/en"
