baseurl = "https://blog.8-p.info/ja/"
languageCode = "ja-jp"
title = "滞舎路日記"
theme = "x17"

Paginate = 5

# https://github.com/spf13/hugo/issues/1252
CanonifyUrls = true

[permalinks]
posts  = "/:year/:month/:day/:filename/"
pages  = "/:filename/"

[blackfriday]
fractions = false

[outputs]
home = ["html", "rss", "json"]

[params]
SourceRoot = "https://github.com/kzys/blog/tree/master/ja"
