baseurl = "https://blog.8-p.info/ja/"
languageCode = "ja-jp"
title = "blog.8-p.info"
theme = "x17"

Paginate = 5

hasCJKLanguage = true

# https://github.com/spf13/hugo/issues/1252
CanonifyUrls = true

[permalinks]
posts  = "/:year/:month/:day/:filename/"
pages  = "/:filename/"

[blackfriday]
fractions = false

[outputs]
home = ["html", "rss", "json"]

[params]
SourceRoot = "https://github.com/kzys/blog/tree/master/ja"

# Goldmark is the default since 0.60,
# but it doesn't have a way to make footnote anchors unique.
[markup]
defaultMarkdownHandler = "blackfriday"

[markup.blackFriday]
# Make all anchors unique. It looks a bit dirty though.
plainIDAnchors = false
footnoteReturnLinkContents = "↩︎"
footnoteAnchorPrefix = ""
