name: pr

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: python -m pip install --user --upgrade https://github.com/kzys/nb2hugo/tarball/blog
    - run: ~/.local/bin/nb2hugo --help
    - run: make
