name: master

on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - run: python -m pip install --user --upgrade https://github.com/kzys/nb2hugo/tarball/blog
    - run: python -m pip install --user s3cmd
    - run: PATH=~/.local/bin:$PATH make
    - run: PATH=~/.local/bin:$PATH make upload
      env:
        AWS_EC2_METADATA_DISABLED: true
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
